#!/bin/env bash

# ---------------- #
# COLOR VARIABLES  #
# ---------------- #

export NOSTYLE='\033[0m'
export NS='\033[0m'

export RED='\033[0;31m'
export GREEN='\033[0;32m'
export ORANGE='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHTGRAY='\033[0;37m'
export DARKGRAY='\033[1;30m'
export LIGHTRED='\033[1;31m'
export LIGHTGREEN='\033[1;32m'
export YELLOW='\033[1;33m'
export LIGHTBLUE='\033[1;34m'
export LIGHTPURPLE='\033[1;35m'
export LIGHTCYAN='\033[1;36m'
export WHITE='\033[1;37m'

# ----------- #
# TEXT STYLES #
# ----------- #

export BOLD='\033[1m'
export DIM='\033[2m'
export ITALIC='\033[3m'
export UNDERLINE='\033[4m'
export BLINKING='\033[5m'
export REVERSE='\033[7m'
export INVISIBLE='\033[8m'

# ------------------------- #
# ENVIRONMENT CONFIGURATION #
# ------------------------- #

# The shell config file of choice
export CONFIGRC='.zshrc'

# Directory containing the config file modules
export CONFIG_DIR="$HOME/.dotfiles"

# Set the default editor in Terminal
export EDITOR="/usr/bin/nano"

# ------------ #
# BINARY PATHS #
# ------------ #

# Default PATH (Arch Linux)
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin"

# Additional defaults for macOS
export PATH="$PATH:/usr/sbin:/sbin"

# Perl bin paths
export PATH="$PATH:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"

# MySQL
export PATH="$PATH:/usr/local/mysql/bin"

# git
export PATH="$PATH:/usr/local/git/bin:/sw/bin"

# Python (macOS)
export PATH="$PATH:$HOME/Library/Python/3.8/bin"

# Global Composer PATH
export PATH="$PATH:$HOME/.composer/vender/bin"

# Path to cargo installed binaries
export PATH="$PATH:$HOME/.cargo/bin"

# .dotfiles bin path (custom executables)
export PATH="$PATH:$CONFIG_DIR/bin"

# ---------------- #
# GLOBAL NODE PATH #
# ---------------- #

export NODE_PATH="/usr/local/lib/node_modules"
