#!/bin/sh

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then

 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do

  [ -x "$f" ] && . "$f"

 done

 unset f

fi

xclock -geometry 50x50-1+1 &
xterm -geometry 80x50+494+51 &
xterm -geometry 80x20+494-0 &
feh --bg-fill --randomize /home/rootr/wallpapers/anime/* &

# Execute the i3-gaps windows manager
exec i3
